### 测试登录
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "18627967620@163.com",
  "password": "123"
}


### 测试API
GET http://localhost:8080/user/api
Accept: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjEwNTU1NzgsImV4cCI6MTcyMTA2Mjc3OCwidXNlckluZm8iOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiMTg2Mjc5Njc2MjBAMTYzLmNvbVwifSJ9.S6Y7zg0PYdznVVEH7nIuWMwIr5Lc_oslI1WkkKU-NIQ

### 测试查询商品
GET http://localhost:8080/goods/all
Accept: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjEwMjg3MTEsImV4cCI6MTcyMTAzNTkxMSwidXNlckluZm8iOiJ7XCJpZFwiOjEsXCJ1c2VybmFtZVwiOlwiMTg2Mjc5Njc2MjBAMTYzLmNvbVwifSJ9.3YsQGjc9BuY0GGUT6NmkxGsRx1wJ2pU7cC_jaEPSNIg

