spring:
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_ecommerce?useSSL=false&serverTimezone=UTC
  application:
    name: authority-center
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ccb2b4f5-3156-4fc3-b81d-06bf528627b8
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9002