spring:
  application:
    name: ecommerce-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ccb2b4f5-3156-4fc3-b81d-06bf528627b8
    gateway:
#      routes:
#        - id: ms-user #请求发送地址
#          uri: lb://ms-user #lb:表示均衡负载
#          predicates:     #断言设置 命中断言则访问设置的uri
#            - Path=/abc/**
#          filters:        #过滤器设置
#            - StripPrefix=1    #命中断言后屏蔽第一个字符串 例如上述的'/abc' #不做这样的过滤处理可能会出现即使命中断言也无法访问正确接口
#        - id: ms-goods
#          uri: lb://ms-goods
#          predicates:
#            - Path=/goods/**
#          filters: MyAuth #添加自定义过滤器
#        - id: ms-balance
#          uri: lb://ms-balance
#          predicates:
#            - Path=/balance/**
#          filters:
#        - id: ms-order
#          uri: lb://ms-order
#          predicates:
#            - Path=/order/**
#          filters:


server:
  port: 7000